import Anthropic from '@anthropic-ai/sdk';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEBSITE_ROOT = join(__dirname, '..');
const PAGE_PATH = join(WEBSITE_ROOT, 'pages', 'firebase-totp-mfa-setup.tsx');
const OUTPUT_DIR = join(WEBSITE_ROOT, '.content-suggestions');

const PROMPT_TEMPLATE = `You are a technical writer reviewing a developer documentation page for the firebase-totp-mfa kit.

The kit is a shadcn-style CLI that adds Firebase Identity Platform TOTP MFA to Next.js apps in one command. Commands are:
- \`npx firebase-totp-mfa add next --area /admin --issuer "MyApp"\` — install
- \`npx firebase-totp-mfa enable --project YOUR-PROJECT-ID\` — enable Identity Platform TOTP
- \`npx firebase-totp-mfa verify\` — print manual verification scenarios

Below is the current page (Next.js Pages Router TSX). Suggest ONE concrete improvement: clarify wording, add a missing edge case, update an outdated reference, or add a useful code snippet. Output the improvement as a unified diff against the source TSX file.

Constraints:
- Keep all existing JSX structure intact
- English only (this page is the English variant)
- Reference CLI commands accurately
- No marketing fluff
- Max 30 lines of diff

Current page source:

\`\`\`tsx
{{PAGE_SOURCE}}
\`\`\`
`;

function todayUtc(): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(now.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

async function main() {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('ANTHROPIC_API_KEY is required');
    process.exit(1);
  }

  const pageSource = readFileSync(PAGE_PATH, 'utf-8');
  const prompt = PROMPT_TEMPLATE.replace('{{PAGE_SOURCE}}', pageSource);

  const client = new Anthropic({ apiKey });

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 2000,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content
    .filter((block): block is Anthropic.TextBlock => block.type === 'text')
    .map((block) => block.text)
    .join('\n');

  mkdirSync(OUTPUT_DIR, { recursive: true });
  const outPath = join(OUTPUT_DIR, `${todayUtc()}.md`);
  const body = `# Content suggestion — ${todayUtc()} (UTC)

Generated by \`website/scripts/generate-content.ts\` against \`pages/firebase-totp-mfa-setup.tsx\`.

Review, apply manually if useful, or close the PR if not.

---

${text}
`;
  writeFileSync(outPath, body, 'utf-8');
  console.log(`Suggestion written to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
